/*
 *   OpenEMS IO bestep bundle
 *
 *   Written by Christian Poulter.
 *   Copyright (C) 2025 Christian Poulter <devel(at)poulter.de>
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 *   SPDX-License-Identifier: AGPL-3.0-or-later
 *
 */

package de.poulter.openems.edge.io.bestep;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(
    name = "IO bestep",
    description = "Implements the bestep modbus 4 IO port interface."
)
@interface Config {

    @AttributeDefinition(name = "Component-ID", description = "Unique ID of this component")
    String id() default "io0";

    @AttributeDefinition(name = "Alias", description = "Human-readable name of this component; defaults to component-id")
    String alias() default "";

    @AttributeDefinition(name = "Is enabled?", description = "Is this component enabled?")
    boolean enabled() default true;

    @AttributeDefinition(name = "Modbus-ID", description = "Id of modbus bridge.")
    String modbus_id() default "modbus0";

    @AttributeDefinition(name = "Modbus Unit-ID", description = "The unit-id of the modbus device.")
    int modbusUnitId() default 1;

    @AttributeDefinition(name = "Activate Channel Mapper", description = "Maps state of input to output channels.")
    boolean channelMapper() default false;

    @AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'modbus-id'.")
    String Modbus_target() default "(enabled=true)";

    String webconsole_configurationFactory_nameHint() default "IO bestep [{id}]";

}
