/*
 *   OpenEMS EVCS Heidelberg Energy Control bundle
 *
 *   Written by Christian Poulter
 *   Copyright (C) 2025 Christian Poulter <devel(at)poulter.de>
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 *   SPDX-License-Identifier: AGPL-3.0-or-later
 *
 */

package de.poulter.openems.edge.evcs.heidelberg.energy.control;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.evcs.api.PhaseRotation;

@ObjectClassDefinition(
    name = "EVCS Heidelberg Energy Control (Managed)",
    description = "Heidelberg Energy Control charging station (Managed)"
)
@interface Config {

    @AttributeDefinition(name = "Component-ID", description = "Unique ID of this component")
    String id() default "evcs0";

    @AttributeDefinition(name = "Alias", description = "Human-readable name of this component; defaults to component-id")
    String alias() default "";

    @AttributeDefinition(name = "Is enabled?", description = "Is this component enabled?")
    boolean enabled() default true;

    @AttributeDefinition(name = "Debug Mode", description = "Activates the debug mode")
    boolean debugMode() default false;

    @AttributeDefinition(name = "Modbus-ID", description = "Id of modbus bridge.")
    String modbus_id() default "modbus0";

    @AttributeDefinition(name = "Modbus Unit-ID", description = "The unit-id of the modbus device.", required = true)
    int modbusUnitId() default 1;

	@AttributeDefinition(name = "Minimum hardware current", description = "Minimum charging current of the charger per phase in mA.", required = true)
	int minCurrent() default 6000;

	@AttributeDefinition(name = "Maximum hardware current", description = "Maximum charging current of the charger per phase in mA.", required = true)
	int maxCurrent() default 16000;

	@AttributeDefinition(name = "Configuration Interval", description = "Interval the configuration is send to the evcs in seconds.", required = true)
    int configurationIntervall() default 60;

	@AttributeDefinition(name = "Watchdog Timeout", description = "Evcs falls back to failsafe current after timeout in seconds.", required = true)
    int watchdogTimeout() default 120;

	@AttributeDefinition(name = "Failsage current", description = "Maximum charging current in case of communication timeout in mA.", required = true)
    int failsafeCurrent() default 0;

	@AttributeDefinition(name = "Minimum time till charging limit taken", description = "Minimum time the evcs has to take charging limit in seconds.", required = true)
    int minimumTimeTillChargingLimitTaken() default 30;

	@AttributeDefinition(name = "Phase rotation", description = "The way in which the phases are physically rotated.", required = true)
	PhaseRotation phaseRotation() default PhaseRotation.L1_L2_L3;

    @AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'modbus-id'.")
    String Modbus_target() default "(enabled=true)";

    String webconsole_configurationFactory_nameHint() default "EVCS Heidelberg Energy [{id}]";

}
